language: ruby
sudo: false
addons:
  apt:
    packages:
    - mafft  
before_install:
  - gem update --system
  - export RUBYOPT="-W1"
before_script:
  - mkdir -p $TRAVIS_BUILD_DIR/test/data/out
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1